// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9CWKGWgt_7XsQ66gxL4-E9uTXbNqoV68',
    appId: '1:396958759167:web:1fecacfbe6350e3a06f4ca',
    messagingSenderId: '396958759167',
    projectId: 'libraryapp-3bfac',
    authDomain: 'libraryapp-3bfac.firebaseapp.com',
    storageBucket: 'libraryapp-3bfac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4EhDTmDOTIMDSdej8i6mRnG1MeeeXPO8',
    appId: '1:396958759167:android:7e6d6c555268374d06f4ca',
    messagingSenderId: '396958759167',
    projectId: 'libraryapp-3bfac',
    storageBucket: 'libraryapp-3bfac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyKtCeLsW_8t6LcoDbnynsus3EvXAgvIY',
    appId: '1:396958759167:ios:fca8a9d16b32450006f4ca',
    messagingSenderId: '396958759167',
    projectId: 'libraryapp-3bfac',
    storageBucket: 'libraryapp-3bfac.appspot.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyKtCeLsW_8t6LcoDbnynsus3EvXAgvIY',
    appId: '1:396958759167:ios:fca8a9d16b32450006f4ca',
    messagingSenderId: '396958759167',
    projectId: 'libraryapp-3bfac',
    storageBucket: 'libraryapp-3bfac.appspot.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9CWKGWgt_7XsQ66gxL4-E9uTXbNqoV68',
    appId: '1:396958759167:web:42a225fd9fada79306f4ca',
    messagingSenderId: '396958759167',
    projectId: 'libraryapp-3bfac',
    authDomain: 'libraryapp-3bfac.firebaseapp.com',
    storageBucket: 'libraryapp-3bfac.appspot.com',
  );

}